# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhKKLnkRuKBiTVRAJHIqssM18KhtJw9L
"""

def print_board():
   board = [[' ' for i in range(3)] for j in range(3)]
   print(board)

def main():
  print_board()

main()